version: '3'

services:
  mysql:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_HOST: host
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: database
      TZ: 'Asia/Seoul'
    ports:
      - "13306:3306"

  redis:
    image: redis:latest
    container_name: redis
    hostname: host
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=database
